<?php
/**
 * This file is part of Queue Component with Swoole.
 *
 * @link     https://github.com/limingxinleo/x-swoole-queue
 * @contact  limingxin@swoft.org
 * @license  https://github.com/limingxinleo/x-swoole-queue/blob/master/LICENSE
 */
namespace Tests;

use PHPUnit\Framework\TestCase as UnitTestCase;
use Xin\Redis;
use Xin\Support\File;

abstract class TestCase extends UnitTestCase
{
    public $redis;

    public $file = TESTS_PATH . '/test.cache';

    public $logFile = TESTS_PATH . '/test.log';

    public function __construct($name = null, array $data = [], $dataName = '')
    {
        $config = include TESTS_PATH . '/_ci/config.php';

        $host = $config['redisHost'];
        $auth = $config['redisAuth'];
        $db = $config['redisDb'];
        $port = $config['redisPort'];

        $this->redis = Redis::getInstance($host, $auth, $db, $port);

        parent::__construct($name, $data, $dataName);
    }

    protected function setUp()
    {
        File::getInstance()->put($this->file, 'init');
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
