<?php
// +----------------------------------------------------------------------
// | TestCase.php [ WE CAN DO IT JUST THINK IT ]
// +----------------------------------------------------------------------
// | Copyright (c) 2016-2017 limingxinleo All rights reserved.
// +----------------------------------------------------------------------
// | Author: limx <715557344@qq.com> <https://github.com/limingxinleo>
// +----------------------------------------------------------------------
namespace Tests;

use PHPUnit\Framework\TestCase as UnitTestCase;
use Tests\Rpc\App\TestClient;
use Xin\Redis;
use Xin\Support\File;

abstract class TestCase extends UnitTestCase
{
    public $redis;

    public $file = TESTS_PATH . '/test.cache';

    public $logFile = TESTS_PATH . '/test.log';

    public function __construct($name = null, array $data = [], $dataName = '')
    {
        $config = include TESTS_PATH . '/_ci/config.php';

        $host = $config['redisHost'];
        $auth = $config['redisAuth'];
        $db = $config['redisDb'];
        $port = $config['redisPort'];

        $this->redis = Redis::getInstance($host, $auth, $db, $port);

        parent::__construct($name, $data, $dataName);
    }

    protected function setUp()
    {
        File::getInstance()->put($this->file, 'init');
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
